version: "3"
services:
  frontend:
    image: cjstkrak/docker-multi-app-frontend
    container_name: app_frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m

  nginx:
    restart: always
    image: cjstkrak/docker-multi-app-nginx
    container_name: app_nginx
    ports:
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: cjstkrak/docker-multi-app-backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    environment:
      - MYSQL_HOST: example
      - MYSQL_USER: example
      - MYSQL_ROOT_PASSWORD: example
      - MYSQL_DATABASE: myapp
      - MYSQL_PORT: 3306
